server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  server:
    port: 8091
    address: ${GRPC_SERVER_ADDRESS}
    statusEnabled: true
spring:
  data:
    mongodb:
      uri: ${MONGO_DB_URI}
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: ru.tinkoff.academy.rancher.conf.PostgisDialect
        physical_naming_strategy: com.vladmihalcea.hibernate.type.util.CamelCaseToSnakeCaseNamingStrategy

landscape:
  url: ${LANDSCAPE_SERVICE_URL}