version: '3.8'

networks:
  internal:
    driver: bridge

services:
  handyman:
    build:
      context: ../HandymanService/
    container_name: handyman
    ports:
      - "8080:8080"
      - "8090:8090"
    environment:
      - grpc.server.address=0.0.0.0
    networks:
      - internal
  rancher:
    build:
      context: ../RancherService/
    container_name: rancher
    ports:
      - "8081:8081"
      - "8091:8091"
    environment:
      - grpc.server.address=0.0.0.0
    networks:
      - internal
  landscape:
    build:
      context: ../LandscapeService/
    container_name: landscape
    ports:
      - "8082:8082"
    environment:
      - grpc.client.HandymanService.address=handyman:8090
      - grpc.client.RancherService.address=rancher:8091
    depends_on:
      - handyman
      - rancher
    networks:
      - internal
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - internal
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "9095:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - internal
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres