version: '3.8'

networks:
  internal:
    driver: bridge

services:
  handyman:
    build:
      context: ../HandymanService/
    container_name: handyman
    ports:
      - "8080:8080"
      - "8090:8090"
    env_file:
      - environment/handyman/.env
    depends_on:
      - landscape
      - mongo
    networks:
      - internal
  rancher:
    build:
      context: ../RancherService/
    container_name: rancher
    ports:
      - "8081:8081"
      - "8091:8091"
    env_file:
      - environment/rancher/.env
    depends_on:
      - landscape
      - mongo
    networks:
      - internal
  landscape:
    build:
      context: ../LandscapeService/
    container_name: landscape
    ports:
      - "8082:8082"
    env_file:
      - environment/landscape/.env
    depends_on:
      - postgres
    networks:
      - internal
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - internal
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    env_file:
      - environment/grafana/.env
    depends_on:
      - prometheus
    networks:
      - internal
  postgres:
    image: postgis/postgis:15-3.3
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - environment/postgres/.env
    networks:
      - internal
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - internal

volumes:
  postgres-data:
  prometheus_data:
  grafana_data: