global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "vogorode"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
      - targets: [ 'host.docker.internal:8081' ]
      - targets: [ 'host.docker.internal:8082' ]