global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "vogorode"
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'handyman:8080' ]
      - targets: [ 'rancher:8081' ]
      - targets: [ 'landscape:8082' ]