server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  server:
    port: 8090
    address: 127.0.0.1
status:
  grpc:
    enabled: true