@startuml Context
!include <C4/C4_Container>

Person(handyman, "Handyman", "Исполнитель, предоставляющий сервис")
Person(rancher, "Rancher", "Владелец участков, заказывающий работу")
Person(admin, "Admin", "Администратор приложения")

System(vogorode, "VOgorode", "Проект представляет собой систему предоставляющую сервис по проведению ландшафтных работ клиентам распределённым географически. Сервис должен подбирать исполнителей на основании географических координат исполнителя и локации заказчика, списка оказываемых исполнителем работ, а так же рейтинга исполнителя")

Rel(handyman, vogorode, "Управляет своей учётной записью, просматривает заказы", "http")
Rel(rancher, vogorode, "Управляет своей учётной записью, участками, заказами", "http")
Rel(admin, vogorode, "Смотрит состояние сервисов, получает метрики", "http")

SHOW_LEGEND()
@enduml