@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 0,
    "showDetailedClassStructure": true
  },
  "rootClass": "ru.tinkoff.academy.rancher.controller.FieldController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
FieldController249437783[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FieldController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   service: FieldService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create(fieldDto: FieldDto): Field</TD></TR>
<TR><TD ALIGN="LEFT" >+ delete(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(id: Long): Field</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(id: Long, fieldDto: FieldDto): Field</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FieldMapper1579938180[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FieldMapper</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   modelMapper: ModelMapper [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ mapToEntity(fieldDto: InnerFieldDto): Field</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FieldRepository1562809861[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)FieldRepository</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

FieldService586842662[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FieldService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   mapper: FieldMapper [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   rancherRepository: RancherRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   repository: FieldRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ create(fieldDto: FieldDto): Field</TD></TR>
<TR><TD ALIGN="LEFT" >+ delete(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ get(id: Long): Field</TD></TR>
<TR><TD ALIGN="LEFT" >- getRancher(id: Long): Rancher</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(id: Long, fieldDto: FieldDto): Field</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

RancherRepository1562809861[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)RancherRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getStatistics(pageable: Pageable): Page&lt;Statistic&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

'edges    
FieldController249437783 -> FieldService586842662[label="service
[0..1]"];
FieldService586842662 -> FieldMapper1579938180[label="mapper
[0..1]"];
FieldService586842662 -> FieldRepository1562809861[label="repository
[0..1]"];
FieldService586842662 -> RancherRepository1562809861[label="rancherRepository
[0..1]"];
    
}
@enduml