server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  client:
    HandymanService:
      address: ${GRPC_HANDYMAN_SERVICE_URL}
      negotiationType: plaintext
    RancherService:
      address: ${GRPC_RANCHER_SERVICE_URL}
      negotiationType: plaintext
  serviceNames: HandymanService, RancherService
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
