server:
  port: 8082
management:
  endpoints:
    web:
      exposure:
        include: info, prometheus
      base-path:
      path-mapping:
        prometheus: /metrics
        info: /actuator/info
grpc:
  client:
    HandymanService:
      address: "localhost:8090"
      negotiationType: plaintext
    RancherService:
      address: "localhost:8091"
      negotiationType: plaintext
service:
  listOfNames: HandymanService, RancherService
